# Generated by Django 4.2.4 on 2023-08-19 16:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
