# Generated by Django 4.2.4 on 2023-08-21 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0002_remove_categorymodel_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Posts', '0005_alter_postmodel_options_postmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category_posts', to='Categories.categorymodel'),
        ),
    ]
